# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kira McLean
email: email@kiramclean.com
description: > # this means to ignore newlines until "baseurl:"
  Canadian web developer from the East Coast. Love travelling and politics. Trying to spread reason, quickly realizing how screwed we are.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kiramclean.com" # the base hostname & protocol for your site
twitter_username: "@kiraemclean"
github_username: kiramclean
permalink: /blog/:categories/:title/
gems:
  - octopress-autoprefixer

# Build settings
markdown: kramdown
