baseurl = "https://kiramclean.com/"
canonifyurls = true
disqusShortname = 'kiramclean'
googleAnalytics = "UA-57190325-3"
languageCode = "en-CA"
pygmentsCodeFences = true
pygmentsstyle = "friendly"
title = "Kira McLean"

[permalinks]
  fixed = ":title/"
  blog = "blog/:slug/"

[params]
  Author = "Kira McLean"
  DateForm = "Jan 2, 2006"
  Description = "A blog about my journey learning to code and some other things."
  Email = "email@kiramclean.com"
  GitHub = "//github.com/kiramclean"
  LinkedIn = "//linkedin.com/in/kiramclean"
  Twitter = "//twitter.com/kiraemclean"

[blackfriday]
	hrefTargetBlank = true

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
